version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    json_formatter:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

loggers:
    anyconfig:
        level: WARNING
        handlers: [console]
        propagate: no

    azure:
        level: ERROR
        handlers: [console]
        propagate: no

    kedro.framework:
        level: WARNING
        handlers: [console]
        propagate: no

    kedro.io:
        level: WARNING
        handlers: [console]
        propagate: no

    kedro.pipeline:
        level: WARNING
        handlers: [console]
        propagate: no

    snowflake.connector.cursor:
        level: WARNING
        handlers: [console]
        propagate: no

    snowflake.connector.json_result:
        level: WARNING
        handlers: [console]
        propagate: no

    hyperopt:
        level: ERROR
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console]
